# Generated by Django 4.2.9 on 2024-01-26 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], default=0)),
                ('text', models.TextField()),
                ('word_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('points', models.PositiveIntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_speed', models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0, max_digits=4)),
                ('top_speed', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4)),
                ('average_speed_last_ten', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4)),
                ('races_won', models.PositiveBigIntegerField(blank=True, db_index=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_speed', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=4)),
                ('won', models.BooleanField(default=False)),
                ('text_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typing_comp.textchallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
