# Generated by Django 4.2.9 on 2024-01-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_comp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textchallenge',
            name='points',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='textchallenge',
            name='word_count',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0),
        ),
    ]
