# Generated by Django 4.2.9 on 2024-01-30 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typing_comp', '0003_userprofile_bio_userprofile_fist_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
